### ISSUE TITLE
Error: is.null(pData) | class(pData) == "data.frame" are not all TRUE

### ISSUE THREAD

**Issue by EBJames** [alyssafrazee/ballgown#110]
First of all, sorry if this is the wrong place to ask a question! Let me know if there's a better place, or if I should just try to work this out on my own.

I've just started working with ballgown using some data from HISAT2/Stringtie.

I have two transcriptomes from the same species under different treatments and I'm trying to find differentially expressed genes between them.

Each of these samples is in a different folder in 'extdata' ('Ap_B', and 'Ap_Wi'). The data loads fine using:

`bg = ballgown(dataDir=data_directory, samplePattern='Ap_', meas = "all")`

But this doesn't include the pData. I want the differential expression between 'Ap_B' and 'Ap_Wi'. I made a .csv: 

'ID', 'Treat'
'Ap_B', 'Bac'
'Ap_Wi', 'Wi'

I tried to enter this as the pData: `bg = ballgown(dataDir=data_directory, samplePattern='Ap_', meas = "all", pData = treatment_table)`

And R prints:
`Error: is.null(pData) | class(pData) == "data.frame" are not all TRUE`

I know this is something I'm doing wrong entering the pData, but if anyone out there can give me some pointers on how to enter the pData properly that'd be amazing!

-Ed

**Comment by alyssafrazee** [comment]
What type of object is `treatment_table`? You will need to load the csv into R and make it a data frame in order to pass it as the `pData` argument. You can do this with something like `treatment_table <- read.csv('/whatever/file/name.csv')` and then you should be able to pass treatment_table as you were before.

Note that you will not be able to do statistical differential expression ("stattest") on this data set since there is only 1 sample in each group (see [FAQ #4](http://alyssafrazee.com/faq/)).

Hope this helps!
