### ISSUE TITLE
Adding gene names to ballgown object gexpr(bg)

### ISSUE THREAD

**Issue by mariatraka** [alyssafrazee/ballgown#119]
Hi,
(I've also posted in Biostars here: [https://www.biostars.org/p/281932/] as I need a quick fix)

I'm having an issue with adding names to the gene expression of a bg object. It seems that the texpr$gene_id has multiple entries for the same MSTRGx (as expected considering it's different isoforms for the same gene) but unfortunately for a lot of the genes the first one of the texpr entries is "." and not the actual gene name. This results in my gene names having lots of ".". How can i work around this? I am missing a lot of genes here from all my downstream functional analysis.
Can you help?
Thanks,
Maria

```
gene_expression_ESC = gexpr(bg_ESC_89)
indicesG <- match(rownames(gene_expression_ESC), texpr(bg_ESC_89, 'all')$gene_id)
gene_names_F <- texpr(bg_ESC_89, 'all')$gene_name[indicesG]
gene_names_T <- texpr(bg_ESC_89, 'all')$t_name[indicesG]
gene_expression_ESC_N <- data.frame(geneNames=gene_names_F,ensIDs=gene_names_T, gene_expression_ESC) 


```

**Comment by alyssafrazee** [comment]
Hi @mariatraka --

What assembly software did you use as input for your ballgown object? 

I suspect the `*` entries are due to how isoforms & genes are labeled in the output of whatever assembly software you used (Cufflinks, Stringtie, etc). When ballgown creates `texpr`, it's reading in the assembly output, so it will just copy whatever's there. Have you checked the input (`.ctab`) files for ballgown to see if the stars are there as well?

I'm going to close this because I don't think this is a ballgown bug, but feel free to reopen if you do discover an issue with the way ballgown is reading in the ctab data.

**Comment by mariatraka** [comment]
Thanks Alyssa,
I'm using stringtie and indeed the t_data.ctab files contain "." for some of the entries in gene_name, which suggests as you say that it is coming from the assembler stringtie rather than ballgown. However, when ballgown is used for gene analysis it might be worth to scan for actual entries within a gives MSTRGx, rather than reporting the first one, which sometimes is the ".".
Thanks for the help. Maria
