### ISSUE TITLE
How to get fold change when use ballgown

### ISSUE THREAD

**Issue by xiechangxiao** [alyssafrazee/ballgown#140]
I have a quesition about how to get fold change when use ballgown ?
my scripts as:

![ballgown](https://user-images.githubusercontent.com/35715828/38654389-a1c31a8a-3e41-11e8-8d71-586c622dc4e4.jpg)

and I get an abnormal fold change as : 
![treatvscontrol](https://user-images.githubusercontent.com/35715828/38654562-8d0542fc-3e42-11e8-830d-709979c2294f.jpg)

I would be very grateful to you If you can tell me the principle of analysis, Thank you.

**Comment by alyssafrazee** [comment]
Hi there! The Github repo is a place for bug reports (problems with the software itself) -- this looks like an analysis question, which we recommend posting at support.bioconductor.org (since the ballgown maintainers are unfortunately unable to provide specific consulting on analyses). Thanks and best wishes!
