### ISSUE TITLE
Ballgown Expression Matrix - Normalization?

### ISSUE THREAD

**Issue by clayfos** [alyssafrazee/ballgown#144]
Apologies if this is explained somewhere else, I have not found an answer yet.  I have analyzed a group of samples using Hisat2->StringTie->Ballgown.  I then outputted an expression matrix of FPKM values for a group of samples using the gexpr function in Ballgown.  I am curious though if these values have been normalized beyond just calculating FPKM, such as how Cuffdiff normalizes FPKMs using the median of the geometric means of fragment counts across all libraries.  Or is this something that might happen at the StringTie step?  I ask because I get significantly different FPKM distributions when using the FPKM values of the same samples from Ballgown vs previous/old analyses using Cuffdiff.

**Comment by alyssafrazee** [comment]
Feel free to take a look at the source code for "gexpr" -- this function
attempts to "back out" the gene-level expression value based on the
isoform-level FPKM values. This isn't really a standard approach, since
FPKM isn't necessary for whole-gene-level measurements (measuring based on
counts of aligned reads are totally appropriate in that case). I don't know
how Cuffdiff would get gene-level expression, but it's likely not the same
as ballgown.

The FPKM values in ballgown are simply read in from the alignment step
beforehand -- so the distributions you're seeing in texpr(bg) are
calculated directly from StringTie (and questions about that should be
directed toward folks more familiar with StringTie's algorithms).

The only normalization ballgown does is to adjust for library size when
doing differential expression testing (see ?stattest and the extended
description in the original manuscript).

Hope this helps! In the future, these types of questions are probably
better suited for support.bioconductor.org with the "ballgown" tag -- this
repo is mostly for reporting technical bugs/issues with the software
itself. There's a wider community over on the Bioc forums that can help
with questions like this one :)

**Comment by clayfos** [comment]
Ah I understand.  Thanks for your help, Alyssa!

**Comment by lakshmi9c** [comment]
Hi,
I am working on a similar project in ballgown. I have loaded the ballgown objects in R and need to normalise the data before DGE analysis.  I tried calcNormFactors() using edgeR, but that needs matrix input, instead I have a ballgown object. Could you please guide me on how to normalise the data from ballgown using R functions?

**Comment by alyssafrazee** [comment]
hi @lakshmi9c, per my earlier comment above and others, these sorts of questions are not bugs in ballgown but rather are questions on how to use the package and perform analysis, so we recommend support.bioconductor.org for that.

for this question -- per the ballgown vignette, the object itself is not a matrix but there are several slots in `expr` that are matrices, so if you need matrix input you should start there. documentation from the vignette: https://github.com/alyssafrazee/ballgown#expr.

good luck!
