### ISSUE TITLE
error in statistical function stattest

### ISSUE THREAD

**Issue by fatimarasool** [alyssafrazee/ballgown#152]
Hi,
I have encountered an error while running the stattest function of ballgown
 I have run the command as 
`> results_transcripts = stattest(bg_chrX_filt,feature= c("gene","exon","intron","transcript"),covariate="part", getFC=TRUE,meas="FPKM", timecourse = FALSE, df=2)`
The error was 

> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

Again I modified the above command. The command is 
`> results_transcripts = stattest(bg_chrX_filt,feature= c("gene","exon","intron","transcript"),covariate="part", getFC=TRUE,meas="FPKM", timecourse = TRUE)`
The error was 

> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
In addition: Warning message:
In stattest(bg_chrX_filt, feature = c("gene", "exon", "intron",  :
  Not enough timepoints (or values of covariate) to fit a spline model with 4 degrees of freedom. Statistical tests will be run treating time as categorical. You can also re-run the analysis with decreased df.

Please tell me how to resolve these error

**Comment by fatimarasool** [comment]
why anyone did not reply to this error?

**Comment by alyssafrazee** [comment]
Hi! This repository is for reporting bugs in the ballgown package. For analysis problems, we recommend checking out support.bioconductor.org, or consulting with a bioinformatician at your institution.

But for this time, hopefully the following information will help!
* in your first command, `df=2` is not necessary because you have specified `timecourse=FALSE`. 
* in both commands, we recommend choosing one feature rather than providing all 4. `match.arg` (used internally) appears to default to just the first, so this is equivalent to running with `feature='gene'`. 
* in your second command, the warning message should provide useful information: your time variable has fewer than 4 timepoints, so you cannot use a spline with 4 degrees of freedom (there isn't enough data).
* Finally, and hopefully most helpfully: the contrasts error comes when you are fitting a model and you have a factor variable with only 1 level. I would guess this means that the variable `pData(`bg_chrX_filt`)$part is single-value, i.e., only has 1 possible value. To fit models, you need at least 2 values of `covariate`. More info on this type of error and debugging it here: https://stackoverflow.com/questions/44200195/how-to-debug-contrasts-can-be-applied-only-to-factors-with-2-or-more-levels-er

Good luck!
