### ISSUE TITLE
Quite different gene expression calculated by stringtie and ballgown

### ISSUE THREAD

**Issue by weiwFu** [alyssafrazee/ballgown#161]
Hi, I use stringtie to calculate the gene-level expression (stringtie -A ./panDRR163659/panDRR163659.gene_abund -e -B -p 8 -G ARS-UCD1.2.gtf -o ./ panDRR163659/DRR163659.gtf DRR163659.bam). But I found this was quite different from the gene expression calculated by ballgown.

cat ballgown.2.r
library(ballgown)
bg_chrX <- ballgown(dataDir ="/home/panxy/FWW/chicken/", samplePattern ="pan",meas="all")
a<-gexpr(bg_chrX)
write.table(a, file="/chicken/gene_FPKM_chicken.259.txt",sep="\t",quote=FALSE)
 
Can you tell me which calculation is correct and why it makes this difference?

Thank you for your time. 

weiweiFu

**Comment by weiwFu** [comment]
I found stringtie with -A parameter can get gene abundance. For example, the ACBD5 gene has 6 transcripts. the gene abundance is the sum of all transcripts (value: 10.528861).

![图片](https://user-images.githubusercontent.com/52925606/65333938-f9715200-dbf3-11e9-88d2-d09cda94a880.png)
![图片](https://user-images.githubusercontent.com/52925606/65334228-8e744b00-dbf4-11e9-8c84-5149733a4286.png)

However, the ballgown get this gene abundance only "9.54". And for some genes, the results are the same for two software, while others, the results are different. I want to know the reason.

**Comment by ytcheung** [comment]
I have the same problem as you. https://www.biostars.org/p/347423/#347995 <- Seems that there are different quantification methods for calculating FPKM, I guess this may be the reason? But I'm not sure which method does Ballgown use.

**Comment by alyssafrazee** [comment]
Hi there! Ballgown is not really designed for gene-level expression measurement. When we wrote the paper (2014) we designed ballgown specifically to do isoform-level differential expression testing. Gene-level differential expression testing with RNA-seq was well-served by other software, and specifically we recommended tools like DESeq for those problems (since read counts can be calculated directly for genes). The `gexpr` function is a naive but straightforward way to go from isoform-level FPKM measurements to gene-level measurements when absolutely necessary, but if quantifying gene-level expression is what you are after, I would recommend a tool other than ballgown, since again, ballgown's purpose is transcript-level differential expression.
