### ISSUE TITLE
Ballgown without replicates

### ISSUE THREAD

**Issue by hildebs42** [alyssafrazee/ballgown#170]
Hello,

I am attempting to run ballgown on my samples, but I unfortunately do not have replicates. I am getting the following error:

> exon_results = stattest(bg, feature = 'exon', meas = 'rcount', covariate = "cond")
Error in stattest(bg, feature = "exon", meas = "rcount", covariate = "cond") :
  There must be at least two replicates per group. Make sure covariate is categorical; if continuous, consider the timecourse option, or specify your own models with mod and mod0.
> pData(bg)
            id group    cond
1 normal_merge     0      WT
2  tumor_merge     1 WT_TNFa

Is there a way to work around this issue and run without replicates?

Thanks!

**Comment by alyssafrazee** [comment]
No, unfortunately not :( Ballgown uses statistical methods (linear regression) to create its estimates, and essentially all statistical methods require replicates, since they attempt to estimate variability.

If you only have 1 replicate per group, we recommend the simpler approach of directly calculating the per-gene or per-isoform expression difference between the two samples, without using statistical methods to estimate variability. (Any method allowing you to do statistical inference on your results requires replicates, but you can make the difference list for a more exploratory analysis without them).

Good luck!
