### ISSUE TITLE
Normalisation for differential expression analysis using Ballgown 

### ISSUE THREAD

**Issue by lakshmi9c** [alyssafrazee/ballgown#174]
Hi
I'm working on RNA-Seq analysis to get differentially expressed genes between two sample conditions. I'm following the new Tuxedo pipeline- HISAT STRINGTIE BALLGOWN. My concern is about using ballgown package for differential expression analysis of my RNA-Seq data. I have tried looking up manuals/ protocol for running Ballgown on R. But unfortunately, I can't find a standard protocol. I have run all commands correctly as per paper- https://www.nature.com/articles/nprot.2016.095.
• But I don't understand the need to remove low variance transcripts. Isn't low variance transcripts and low gene abundance entirely different? 
• How do I get gene name and gene id without stattest() function on R using ballgown? 
• How is normalisation done for Ballgown?

 I'm unable to proceed after getting the list of gene names and unsure of what the next step is. How should I do normalisation for Ballgown? I'm stuck at this step and would much appreciate any help on how do I proceed in order to get DE genes. Thanks in advance!

**Comment by alyssafrazee** [comment]
Hi there! This seems like an analysis question rather than a ballgown bug report (which is how we use github issues), so I'd recommend posting it at support.bioconductor.org, or asking a bioinformatician at your institution for help. That way, users of the software can help you.

To point you in the right direction for a few of your questions:
- several ballgown co-authors published a Nature Protocols article in 2016, if you'd like to use that as a standard protocol: https://pubmed.ncbi.nlm.nih.gov/27560171/. There are also some tutorials out there by folks following the protocol, for example: https://davetang.org/muse/2017/10/25/getting-started-hisat-stringtie-ballgown/
- removing low-variance transcripts isn't really specific to ballgown. We did this in our analysis and examples because it's standard practice in genomic analysis. If you have no (or little) variability, every tiny change in expression between groups will end up being statistically significant, no matter the practical difference, and transcripts with variability = 0 break the statistical models (since statistical testing requires dividing by the variance or standard deviation).
- gene name and gene ID need to come from somewhere before ballgown in the pipeline. stringtie should give you that info in its output. if you did a de novo assembly, there won't be reference gene names but there should be some sort of an ID in the gtf file. I'd recommend studying the stringtie input to figure out why yours does not have the names/ids you need, and asking in the other forums for help there.
- normalization (what we call "library size adjustment") is done by including the 75th percentile of counts for each replicate as a covariate in the fitted linear model -- see the `libadjust` argument of stattest: https://github.com/alyssafrazee/ballgown/blob/master/R/stattest.R#L52. (I think this is discussed in the supplementary material in the ballgown paper: http://www.nature.com/nbt/journal/v33/n3/full/nbt.3172.html -- there's also a free preprint + supplement on biorxiv as well, which is loading super slowly for me at the moment; sorry for the difficulty there).

best wishes!
