### ISSUE TITLE
Difference between 'gene' & 'transcript' in stat test

### ISSUE THREAD

**Issue by mentorlg** [alyssafrazee/ballgown#178]
Hi
I'd like to find out DEG using Ballgown.
But, I have a problem in stattest.

1. My data set :
>sample <- c("CANN_heat-3h-1", "CANN_heat-3h-2", "CANN_heat-3h-3", "CANN_control-3h-1", "CANN_control-3h-2", "CANN_control-3h-3")
>type <- c("heat", "heat", "heat", "a_control", "a_control", "a_control")

>pheno_data<-data.frame("id"=id, "type"=type)

2. Read expression data from StringTie result
>bg <- ballgown(dataDir = "heat_3h", samplePattern = "CANN", pData=pheno_data)

(filtering out)

>bg_filt = subset(bg, "rowVars(texpr(bg)) >1", genomesubset=TRUE)

3. stat test
>stat_results = stattest(bg, feature='gene', covariate="type", getFC=TRUE, meas="FPKM")
>stat_results_tr = stattest(bg, feature='transcript', covariate="type", getFC=TRUE, meas="FPKM")

Question) 
I wonder why fc, pval, and qval are different between 'stat_results' and 'stat_resuts_tr'.
(Its difference is 'feature')
My data set is 1 gene : 1 transcript, so gexpr and texpr results are same. (I checked results in R)
But, when I compared stattest results with different feature, result values are different (I checked gene_ID and transcript_ID were matched). 
I can't understand this problem.

kindly help, thank you :)
Amelia

**Comment by alyssafrazee** [comment]
Hi there! 

As you point out, `stat_results` is doing differential expression by gene, and `stat_results_tr` is giving you transcript-level differential expression results. Each gene has one or more transcripts (isoforms), so the test results differ because the expression measurements differ. This is expected.

Also, I recommend posting these questions on support.bioconductor.org, or asking a bioinformatician at your institution! This repository hosts the ballgown source code and is intended for reporting bugs in the software, not for general analysis questions. I think you'll get more satisfying answers in a different forum! 😃 

Good luck!
