### ISSUE TITLE
does not work if the data_directory is 'ballgown'

### ISSUE THREAD

**Issue by gouthamatla** [alyssafrazee/ballgown#52]
If the data directory name is ballgown, like data_directory = system.file('ballgown', package='ball gown'), it is not recognising the data dir.

**Comment by alyssafrazee** [comment]
You should really only use the "system.file" command if you are looking for data/files that come with packages. 

In the actually ballgown() constructor command, try using the full file path to the data directory name (as dataDir). 

If you are looking for files that come with ballgown, system.file will not work if you put a space in the name (package='ball gown'), since the package is named "ballgown" not "ball gown".

**Comment by gouthamatla** [comment]
Got it. Thank you.
