### ISSUE TITLE
Error : objects 'metadata', 'isTRUEorFALSE', 'isSingleString' are not exported by 'namespace:IRanges'

### ISSUE THREAD

**Issue by wmy77** [alyssafrazee/ballgown#61]
hello:
      when I install "ballgown" , I come across with such a problem--- 
(Error : objects 'metadata', 'isTRUEorFALSE', 'isSingleString' are not exported by 'namespace:IRanges').
     I'am wondering how to solve that.

**Comment by wmy77** [comment]
my server can't connect to the internet, so I can't use "biocLite" to install R packages.

**Comment by alyssafrazee** [comment]
Could you please paste the exact commands you ran that gave you the error you're seeing? We can debug from there.

Unfortunately this seems like it's a version mismatch between some of your Bioconductor packages, and by far the best way to ensure your versions are compatible is to use biocLite.

**Comment by wmy77** [comment]
1, install "IRanges_2.2.0.tar.gz" and other dependent packages
2, "R CMD INSTALL ballgown_2.0.0.tar.gz"
* installing *source* package 'ballgown' ...
** R
** data
** inst
** preparing package for lazy loading
Error : objects 'metadata', 'isTRUEorFALSE', 'isSingleString' are not exported by 'namespace:IRanges'
ERROR: lazy loading failed for package 'ballgown'

**Comment by alyssafrazee** [comment]
The current version of IRanges (which is the version guaranteed to be compatible with the current version of ballgown) is 2.2.1, so you might try upgrading that and any other dependencies (there are on the order of 30 dependencies when you count dependencies of imported packages, so please look very carefully at every package and its dependencies and make sure you are using the most current version of all those packages).

I checked Ballgown's build status on Bioconductor's build checker (http://www.bioconductor.org/checkResults/release/bioc-LATEST/) and all tests / checks are passing. This means things are working in the current Bioconductor ecosystem, and doesn't indicate any problems here on our end. Since the package is passing checks and does install properly with the recommended method, `biocLite()`, I'm going to close the issue, but feel free to reopen if you do have biocLite issues at any point.
