### ISSUE TITLE
Unable to load data in

### ISSUE THREAD

**Issue by mhoa2245** [alyssafrazee/ballgown#71]
##################

  

Hi,
## For example (Sample1 directory)

Snipe047bg1 ## directory
...Sample1 ## subdirectory
...... e_data.ctab
...... e2t.ctab
...... i_data.ctab
...... i2t.ctab
...... t_data.ctab
...... S1.gtf

## I input per the vignette
library(ballgown) 
data_directory= ('Snipe047bg1')
data_directory
bg=ballgown(dataDir=data_directory, samplePattern='S', meas='all')

####################
## I get the following error:
Thu Oct 22 10:20:17 2015
Thu Oct 22 10:20:17 2015: Reading linking tables
Error in file(file, "rt") : invalid 'description' argument

####################
## I use traceback()
> traceback()
3: file(file, "rt")
2: read.table(list.files(samples[1], "e2t.ctab", full.names = TRUE), 
       header = TRUE, sep = "\t", colClasses = c("integer", "integer"))
1: ballgown(dataDir = data_directory, samplePattern = "Sample", meas = "all")

## Any suggestions?

- Mike

**Comment by JMF47** [comment]
Hi Mike,

What is the full path to the Snipe047bg1 directory, and what is the working directory for the R session when you are calling this?

Best,
Jack

**Comment by mhoa2245** [comment]
Hi Jack,
    I set the working directory as the Snipe047bg1 directory and then designated data_directory as this directory.
    Here's the path: 
setwd("H:/Single Cell RNA-Seq/Data From Rob/Snipe047bg1")
data_directory= ('Snipe047bg1')

I appreciate any suggestions. Thanks again.

- Mike

**Comment by JMF47** [comment]
Could you try
setwd("H:/Single Cell RNA-Seq/Data From Rob")
data_directory= ('Snipe047bg1')

**Comment by mhoa2245** [comment]
Hi Jack, 
   It's gotten past the initial error and seems to be working. Thanks so much.
Regards, 
   Mike

**Comment by JMF47** [comment]
No problems!
Best,
Jack

**Comment by vitaly001** [comment]
I also have same problem. My working directory is set to
setwd('/Volumes/HD2/HISAT_OUTPUT')

data_directory = ('ballgown')
sample_IDs = c("YOUNG_PLUS","YOUNG_MINUS", "OLP_PLUS", "OLD_MINUS")

sample_paths = paste0('/Volumes/HD2/HISAT_OUTPUT/ballgown/', sample_IDs)

When I try to download the data to ballgown 
bg = ballgown(samples=sample_paths, meas='all')

I got same error "Error in ballgown(samples = sample_paths, meas = "all") : 
  Something is wrong: are you missing .ctab files? Do extra files/folders (other than tablemaker output folders) match your samples/dataDir/samplePattern argument(s)?"
When I try to download the data using dataDir

bg_samples = ballgown(dataDir = data_directory, samplePattern = "S", pData=pheno_data, meas = 'all')
I got same error. I hope somebody can help me to solve this problem
Thank you, 
Vit

**Comment by alyssafrazee** [comment]
Hey @vitaly001 --

Could you please post the directory structure of the folder `/Volumes/HD2/HISAT_OUTPUT/ballgown/`? 
(you can see an example "directory structure" in the README: https://github.com/alyssafrazee/ballgown#loading-data-into-r)

It's possible that there's a typo in the third entry of `sample_IDs` in your code above: you have "OLP_PLUS" (do you mean "OLD_PLUS"? just a guess, I don't know the data, but thought I'd check!)

Another thought is that your path seems to specify HISAT output -- you need either Stringtie or Tablemaker output. (i.e., you need files ending in `.ctab`, and only files ending in `.ctab`, in your ballgown directory). This is maybe more likely, since it seems that the `samplePattern` argument would match regardless of any typos in data_directory. 

These two things are just guesses though, I can say more if you paste the full directory structure (please include any and all files listed inside that path).

**Comment by vitaly001** [comment]
First at all, thank you very much. Indeed, because of typo it didn't work. When I corrected the typo it start to read the data. However, I got next message:

Error in ballgown(dataDir = data_directory, samplePattern = "S", pData = pheno_data,  : 
  first column of pData does not match the names of the folders containing the ballgown data.
In addition: Warning message:
In ballgown(dataDir = data_directory, samplePattern = "S", pData = pheno_data,  :
  Rows of pData did not seem to be in the same order as the columns of the expression data. Attempting to rearrange pData...
> pheno_data
   conditions   Age Treatment
1  YOUNG_PLUS YOUNG      PLUS
2 YOUNG_MINUS YOUNG     MINUS
3    OLD_PLUS   OLD      PLUS
4   OLD_MINUS   OLD     MINUS


Regarding the data, in my HISAT_OUTPUT directory I keep the stringtie output in ballgown folder
my directory structure is next:
HD2/
       HISAT_OUTPUT/
                                  ballgown/
                                                 YOUNG_PLUS/
                                                                        e_data.ctab
                                                                        e2t.ctab
                                                                         i_data.ctab
                                                                         i2t.ctab
                                                                         t_data.ctab
                                                                         YOUNG_PLUS.gtf

my working directory is HISAT_OUTPUT
when I try to check the data_directory 
data_directory = system.file('HISAT_OUTPUT', package='ballgown')
data_directory is variable with empty vector
> data_directory
[1] ""

Thank you Alyssa for help
Vit

**Comment by alyssafrazee** [comment]
you should not use `system.file` to create `data_directory`-- `system.file` is used to find files that are shipped with R packages (which is why they're used in the documentation a lot), not files on your local working disk. in the previous example your `data_directory` is `"ballgown"`, which I think was correct.

This doesn't appear to be a bug in the ballgown package, so if you have further questions, please post them on support.bioconductor.org with the ballgown tag! you'll get more help from the wider community there :)

**Comment by KeaNcu** [comment]
Hi 

First I would like to thank everyone for the above comments I had the same issue but its all sorted now. However I have an additional error message

I ran this command:

bg = ballgown(dataDir="Ballgown", samplePattern= "*", pData=pheno_data)

Then i got the below error.

Error in ballgown(samples = c(...  : 
  intron ids were either not the same or not in the same order across samples. double check i_data.ctab for each sample.

Please assist, how can i correct the files and get it to work? Any suggestionsA
 
Kea

**Comment by orhanbellur** [comment]
Hi there
I have a problem related to running ballgown function. Eventhough, I have tried to change working  directory I could not run the code anyway. My working directory :"/home/orhan/my_rnaseq_exp" .
ballgown directory contains  12 subdirectory starting with "ERR...". 
when I tried to work this code:
"bg_chrX <- bg_chrX = ballgown(dataDir = "ballgown", samplePattern = "ERR", pData=pheno_data)"
I got this error:
" Sat Oct 28 11:41:57 2017
Sat Oct 28 11:41:57 2017: Reading linking tables
Sat Oct 28 11:41:57 2017: Reading intron data files
Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  invalid 'row.names' length"

The codes at below which I wrote , respectively:
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0) {
  # assume no output directory argument was given to rnaseq_pipeline.sh
  pheno_data_file <- paste0(getwd(), "/chrX_data/geuvadis_phenodata.csv")
} else {
  pheno_data_file <- args[1]
}

library(ballgown)
library(RSkittleBrewer)
library(genefilter)
library(dplyr)
library(devtools)

getwd() # "/home/orhan/my_rnaseq_exp"

pheno_data <- read.csv(pheno_data_file)

bg_chrX <- bg_chrX = ballgown(dataDir = "ballgown", samplePattern = "ERR", pData=pheno_data)
"
Please assist, how i can deal with this problem? Thanks in advance....
Orhan

**Comment by vitaly001** [comment]
FIRST column of pData should match the names of the folders containing the ballgown data and have common attribute. Could you please show the metadata table structure.

**Comment by orhanbellur** [comment]
Hi there
First of all thank you for your interesting. I could overcome with this problem. İf I am to explain why got this error, I think it caused from old version of string tie. Thank you again...

**Comment by Jiglov** [comment]
@orhanbellur 
What stringtie version was that?

I have 
Error in ballgown(dataDir = ".", samplePattern = "mine") : 
  Something is wrong: are you missing .ctab files? Do extra files/folders (other than tablemaker output folders) match your samples/dataDir/samplePattern argument(s)?
when trying without the pData.
So the ctab files are there, but after stringtie for 12 samples (replicates), I've got only 5 ctab files, stringtie was performed as been described in the HISAT STRINGTIE BALLGOWN paper by Pertea 2016

I've got everything working up to ballgown.

Any help?

**Comment by henrick-aduda** [comment]
> Hi
> 
> First I would like to thank everyone for the above comments I had the same issue but its all sorted now. However I have an additional error message
> 
> I ran this command:
> 
> bg = ballgown(dataDir="Ballgown", samplePattern= "*", pData=pheno_data)
> 
> Then i got the below error.
> 
> Error in ballgown(samples = c(... :
> intron ids were either not the same or not in the same order across samples. double check i_data.ctab for each sample.
> 
> Please assist, how can i correct the files and get it to work? Any suggestionsA
> 
> Kea

Were you able to solve this problem? Facing the same diffculty .

**Comment by Ragingdemo** [comment]
> > Hi
> > First I would like to thank everyone for the above comments I had the same issue but its all sorted now. However I have an additional error message
> > I ran this command:
> > bg = ballgown(dataDir="Ballgown", samplePattern= "*", pData=pheno_data)
> > Then i got the below error.
> > Error in ballgown(samples = c(... :
> > intron ids were either not the same or not in the same order across samples. double check i_data.ctab for each sample.
> > Please assist, how can i correct the files and get it to work? Any suggestionsA
> > Kea
> 
> Were you able to solve this problem? Facing the same diffculty .

I am having the same difficulty
