### ISSUE TITLE
question about stattest 

### ISSUE THREAD

**Issue by michmich76** [alyssafrazee/ballgown#79]
My data contains two groups 'control' and 'treatment' with three replicate, I tan StringTie and then upload the results to R with ballgown:
bg <- 
  ballgown(dataDir="MyDir", samplePattern='sample_', meas='all')
bg
ballgown instance with 76484 transcripts and 6 samples
pData(bg):
         id group
1 sample_18     0
2 sample_19     1
3 sample_45     0
4 sample_46     1
5 sample_72     0
6 sample_73     1

when I run stattest I got only 7 

(out of 76484) transcripts that were  significantly differentially expressed  (q.value <= 0.05)
so I filtered my data with mean FPKM cutoff set to 1, and the I got 25 (out of 26314)  transcripts that were  significantly differentially expressed  (q.value <= 0.05)

Then I filtered my data again, this time  with mean FPKM cutoff set to 2, I got 319 (out of 18625)  transcripts that were  significantly differentially expressed  (q.value <= 0.05)

Can you explain me why does it happen, how come the more I filtered out transcripts I get more DE transcripts in the data?

Thanks
Michal

**Comment by alyssafrazee** [comment]
Hi Michal,

This probably has to do with the fact that less adjustment for multiple testing has to be done when there are fewer tests performed. You can confirm that the calculations are correct by comparing the p-values for the same transcripts under the different filtering scenarios -- the p-values should be the same, but the q-values are likely different.

In the future- since this is more of a statistical/data question than a ballgown issue/bug, you'll probably get better help with this question at support.bioconductor.org!

Closing the issue since I don't think we need to make any ballgown code changes for this, but please feel free to reopen if there is in fact a technical problem with the package.

**Comment by michmich76** [comment]
Thanks :)

On Thu, Apr 14, 2016 at 10:15 PM Alyssa Frazee <notifications@github.com>
wrote:

> Closed #79 <https://github.com/alyssafrazee/ballgown/issues/79>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alyssafrazee/ballgown/issues/79#event-627862917>
>
-- 

Michal Sharabi-Schwager, Ph.D.
Agriculture Research Organization
Volcani Center
P.O.B 6
Bet-Dagan 50250
Israel
Phone: 972-54-2284280
Fax: 972-3-9565691
e-mail: michalsharabi@gmail.com
