### ISSUE TITLE
Transcript and Gene level DE show different results

### ISSUE THREAD

**Issue by TravisCG** [alyssafrazee/ballgown#86]
I have run two DE analysis in the same dataset. First I wanted to find differentially expressed genes, second time differentially expressed transcripts. The number of genes was 750, which is reasonable, but stattest find only 30 transcripts, which is biologically strange (the numbers are the significant ones). Do you have any idea what should be behind this differences?

Thank you,
Tibor

**Comment by alyssafrazee** [comment]
Hi Tibor,

This is probably a better question for support.bioconductor.org, which is a Q&A forum for users of BioC packages to ask analysis questions like this. (More people will follow it, and you can figure out if anyone has seen this type of problem before).

Without code or any data here, it's difficult to say what the problem might be, or if there is one. What commands did you run? What significance cutoffs did you use? One thing I thought of was that there are probably a lot _more_ transcripts than there are genes in your data set, which means that if you use q-values to adjust for multiple testing, the q-values for transcripts are likely to be larger in general (since more tests are being done). Or maybe there wasn't enough data (i.e., n was too small) for many individual transcripts to be called DE, but there was enough data for the entire gene to give more power to the statistical test. However, without more information it's hard to say what's going on. 

If you do find a bug in ballgown (e.g., DE results are incorrect on, say, a simulated data set) please do file it here! But for more specific help on this question I'd recommend support.bioconductor.org.
