### ISSUE TITLE
Is it possible to get gene count (raw and not normalised) from Ballgown?

### ISSUE THREAD

**Issue by eudoraleer** [alyssafrazee/ballgown#94]
I was wondering if I could get gene counts directly from ballgown objects after Stringtie, without using prepDE.py script as suggested?

Thanks!

**Comment by alyssafrazee** [comment]
Sorry, ballgown doesn't currently have a gene counting tool since it's designed for isoform-level DE analysis. I would recommend using the prepDE.py script since that's what's suggested by the Stringtie authors and is designed for exactly that purpose :) If that script causes problems I'd recommend following whatever procedure is suggested by the Stringtie authors for filing bug reports.

**Comment by eudoraleer** [comment]
Thank you so much alyssafrazee. A side question, why is there multiple transcripts of the same gene been observed in the gene count output from prepDE.py? Are those isoforms of the same gene? Thanks.

**Comment by alyssa-stripe** [comment]
> Are those isoforms of the same gene? 

Yes, exactly.
